version: "3.8"

services:
  backend:
    build:
      context: Backend
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: Frontend
    container_name: frontend
    ports:
      - "80:80"
      - "3000:80"
    environment:
      - URL_BACKEND=http://127.0.0.1:8080
    depends_on:
      - backend